public class Main {
    public static void main(String[] args) {
        System.out.println("Exercise 1");
        byte a = 127;
        System.out.println("Значение переменной 'a'" + " с типом BYTE равно " + a);
        short b = 32000;
        System.out.println("Значение переменной 'b'" + " с типом SHORT равно " + b);
        int c = 2000000000;
        System.out.println("Значение переменной 'c'" + " с типом INT равно " + c);
        long d = 100L;
        System.out.println("Значение переменной 'd'" + " с типом LONG равно " + d);
        System.out.println("Exercise 2");
        double aa = 27.12f;
        long bb = 987678965549L;
        float cc = 2.786f;
        short dd = 569;
        short ee = -159;
        int ff = 27897;
        byte ggwp = 67;
        System.out.println("No Data according the exercise!!! )))");
        System.out.println("Exercise 3");
        byte lP = 23;
        byte aS = 27;
        byte eA = 30;
        short sumSheets = 480;
        int shPerPuples = sumSheets / (lP + aS + eA);
        System.out.println("На каждого ученика рассчитано " + shPerPuples + " листов бумаги");
        System.out.println("Exercise 4");
        byte bPer2Min = 16;
        int bPerMin = bPer2Min / 2;
        byte  twM = 20;
        int bPer20Min = bPerMin * twM;
        System.out.println("За 20 минут машина произвела " + bPer20Min + " штук бутылок");
        byte sxM = 60;
        byte twFH = 24;
        int mPerDay = twFH * sxM;
        int bPerDay = mPerDay * bPerMin;
        System.out.println("За сутки машина произвела " + bPerDay + " штук бутылок");
        byte thrD = 3;
        int mPer3Days = mPerDay * thrD;
        int bPer3Days = mPer3Days * bPerMin;
        System.out.println("За 3 суток машина произвела " + bPer3Days + " штук бутылок");
        byte thirtD = 30;
        int mPerMonth = mPerDay * thirtD;
        int bPer30Days = mPerMonth * bPerMin;
        System.out.println("За 30 суток машина произвела " + bPer30Days + " штук бутылок");
        System.out.println("Exercise 5");
        byte totalCan = 120;
        byte whitePClass = 2;
        byte brownPClass =4;
        int totClass = totalCan / (whitePClass + brownPClass);
        int totalWhite = totClass * whitePClass;
        int totalBrown = totClass * brownPClass;
        System.out.println("В школе, где " + totClass + " классов, нужно " + totalWhite + " банок белой краски и " + totalBrown + " банок коричневой краски");
        System.out.println("Exercise 6");
        byte totBan = 5;
        byte banWei = 80;
        int totBanWei = totBan * banWei;
        short milkVol = 200;
        byte milkWei = 105;
        byte milkPorVol = 100;
        int milkPortion = milkVol / milkPorVol;
        int totMilkWei = milkWei * milkPortion;
        byte iceCrBr = 2;
        byte iceCrWei = 100;
        int iceCrTotWei = iceCrBr * iceCrWei;
        byte frEgg = 4;
        byte eggWei = 70;
        int totEggWei = frEgg * eggWei;
        int totalBreakfastWei = totMilkWei + totBanWei + iceCrTotWei + totEggWei;
        System.out.println("Вес завтрака равен " + totalBreakfastWei + " грамм");
        short grInKg = 1000;
        float weiInKg = (float) totalBreakfastWei / grInKg;
        System.out.println("Вес завтрака равен " + weiInKg + " килограмм");
        System.out.println("Exercise 7");
        byte weiGoal = 7;
        short lowLoss = 250;
        short highLoss = 500;
        short grInKgEx7 = 1000;
        float lowLossKg = (float) lowLoss / grInKgEx7;
        float highLossKg = (float) highLoss / grInKgEx7;
        float totDlow = weiGoal / lowLossKg;
        float totDHigh = weiGoal / highLossKg;
        System.out.println("При медленном похудении спортсмену понадобится " + totDlow + " дней");
        System.out.println("При быстром похудении спортсмену понадобится " + totDHigh + " дней");
        int averageLoss = (lowLoss + highLoss) / 2;
        float avLossKg = (float) averageLoss / grInKgEx7;
        float totDAv = weiGoal / avLossKg;
        System.out.println("При умеренном похудении спортсмену понадобится " + totDAv + " дней");
        System.out.println("Exercise 8");
        int mashBefore = 67760;
        int denBefore = 83690;
        int krisBefore = 76230;
        byte oneHunPers = 1;
        float oneHPlusTenPers =  oneHunPers + 0.1f;
        float mashAfter = mashBefore * oneHPlusTenPers;
        float denAfter = denBefore * oneHPlusTenPers;
        float krisAfter = krisBefore * oneHPlusTenPers;
        float mashDif = mashAfter - mashBefore;
        float denDif = denAfter - denBefore;
        float krisDif = krisAfter - krisBefore;
        System.out.println("Маша теперь получает " + mashAfter + " рублей. Годовой доход вырос на " + mashDif + " рублей");
        System.out.println("Денис теперь получает " + denAfter + " рублей. Годовой доход вырос на " + denDif + " рублей");
        System.out.println("Кристина теперь получает " + krisAfter + " рублей. Годовой доход вырос на " + krisDif + " рублей");
    }
}