public class Main {
    public static void main(String[] args) {
        System.out.println("Exercise 1");
        byte a = 127;
        System.out.println("Значение переменной 'a' с типом BYTE равно " + a);
        short b = 32000;
        System.out.println("Значение переменной 'b' с типом SHORT равно " + b);
        int c = 2000000000;
        System.out.println("Значение переменной 'c' с типом INT равно " + c);
        long d = 100L;
        System.out.println("Значение переменной 'd' с типом LONG равно " + d);
        float e = 1.111111f;
        System.out.println("Значение переменной 'e' с типом FLOAT равно " + e);
        double f = 1.111111111111111;
        System.out.println("Значение переменной 'f' с типом LONG равно " + f);
        System.out.println("Exercise 2");
        float aOne = 27.12f;
        long bTwo = 987678965549L;
        float cThree = 2.786f;
        short dFour = 569;
        short eFive = -159;
        short fSix = 27897;
        byte gSeven = 67;
        System.out.println("Exercise 3");
        byte lP = 23;
        byte aS = 27;
        byte eA = 30;
        short sumSheets = 480;
        int sheetsPerPuple = sumSheets / (lP + aS + eA);
        System.out.println("На каждого ученика рассчитано " + sheetsPerPuple + " листов бумаги");
        System.out.println("Exercise 4");
        byte bottlePer2Min = 16;
        int bottlePerMin = bottlePer2Min / 2;
        int bottlePer20Min = bottlePerMin * 20;
        System.out.println("За 20 минут машина произвела " + bottlePer20Min + " штук бутылок");
        int bottlePerDay = 24 * 60 * bottlePerMin;
        System.out.println("За сутки машина произвела " + bottlePerDay + " штук бутылок");
        int bottlePer3Days = 24 * 60 * 3 * bottlePerMin;
        System.out.println("За 3 суток машина произвела " + bottlePer3Days + " штук бутылок");
        int bottlePer30Days = 24 * 60 * 30 * bottlePerMin;
        System.out.println("За 30 суток машина произвела " + bottlePer30Days + " штук бутылок");
        System.out.println("Exercise 5");
        byte totalCan = 120;
        byte whitePaintForClass = 2;
        byte brownPaintForClass =4;
        int totalClass = totalCan / (whitePaintForClass + brownPaintForClass);
        int totalWhite = totalClass * whitePaintForClass;
        int totalBrown = totalClass * brownPaintForClass;
        System.out.println("В школе, где " + totalClass + " классов, нужно " + totalWhite + " банок белой краски и " + totalBrown + " банок коричневой краски");
        System.out.println("Exercise 6");
        byte totalBanana = 5;
        byte bananaWeight = 80;
        int totalBananaWeight = totalBanana * bananaWeight;
        short milkVolume = 200;
        byte milkWeight = 105;
        byte milkPortionVolume = 100;
        int milkPortion = milkVolume / milkPortionVolume;
        int totMilkWeight = milkWeight * milkPortion;
        byte iceCreamBriquette = 2;
        byte iceCreamWeight = 100;
        int iceCreamTotalWeight = iceCreamBriquette * iceCreamWeight;
        byte countOfEgg = 4;
        byte eggWeight = 70;
        int totalEggWeight = countOfEgg * eggWeight;
        int totalBreakfastWeight = totMilkWeight + totalBananaWeight + iceCreamTotalWeight + totalEggWeight;
        System.out.println("Вес завтрака равен " + totalBreakfastWeight + " грамм");
        short gramInKg = 1000;
        float weightInKg = (float) totalBreakfastWeight / gramInKg;
        System.out.println("Вес завтрака равен " + weightInKg + " килограмм");
        System.out.println("Exercise 7");
        byte weightGoal = 7;
        short lowLoss = 250;
        short highLoss = 500;
        short gramInKgExercise7 = 1000;
        float lowLossInKg = (float) lowLoss / gramInKgExercise7;
        float highLossInKg = (float) highLoss / gramInKgExercise7;
        float totalDaysLow = weightGoal / lowLossInKg;
        float totalDaysHigh = weightGoal / highLossInKg;
        System.out.println("При медленном похудении спортсмену понадобится " + totalDaysLow + " дней");
        System.out.println("При быстром похудении спортсмену понадобится " + totalDaysHigh + " дней");
        int averageLoss = (lowLoss + highLoss) / 2;
        float avLossKg = (float) averageLoss / gramInKgExercise7;
        float totDAv = weightGoal / avLossKg;
        System.out.println("При умеренном похудении спортсмену понадобится " + totDAv + " дней");
        System.out.println("Exercise 8");
        int mashaBeforeIncreasing = 67760;
        int denisBeforeIncreasing = 83690;
        int kristinaBeforeIncreasing = 76230;
        int mashaAfterIncreasing = mashaBeforeIncreasing / 10 * 11;
        int denisAfterIncreasing = denisBeforeIncreasing / 10 * 11;
        int kristinaAfterIncreasing = kristinaBeforeIncreasing / 10 * 11;
        int mashaDifference = mashaAfterIncreasing - mashaBeforeIncreasing;
        int denisDifference = denisAfterIncreasing - denisBeforeIncreasing;
        int kristinaDifference = kristinaAfterIncreasing - kristinaBeforeIncreasing;
        System.out.println("Маша теперь получает " + mashaAfterIncreasing + " рублей. Годовой доход вырос на " + mashaDifference + " рублей");
        System.out.println("Денис теперь получает " + denisAfterIncreasing + " рублей. Годовой доход вырос на " + denisDifference + " рублей");
        System.out.println("Кристина теперь получает " + kristinaAfterIncreasing + " рублей. Годовой доход вырос на " + kristinaDifference + " рублей");
    }
}